services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=food-order-ms'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=admin'
    ports:
      - 5432:5432
